# Generated by Django 4.2.9 on 2024-09-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_resultanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
