# Generated by Django 5.1.1 on 2024-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_question_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
